version: '3.8'

services:
  morning-bot:
    build: .
    container_name: morning-greeting-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
